# Advanced Algebra with Python: Working with Matrices

Matrices are rectangular arrays of numbers that play a central role in linear algebra, with applications in linear transformations, solving systems of equations, computer graphics, data science, and more. Python, with libraries like **NumPy** and **SymPy**, makes it easy to manipulate matrices and explore their properties.

---

## Prerequisites

Install the required libraries:

```bash
pip install numpy sympy
```

---

## 1. Creating and Manipulating Matrices

### Using NumPy

In [1]:
import numpy as np

# Create a 2x2 matrix
A = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", A)

# Matrix addition
B = np.array([[5, 6], [7, 8]])
print("A + B:\n", A + B)

# Matrix multiplication
print("A * B (element-wise):\n", A * B)
print("A dot B:\n", np.dot(A, B))  # or A @ B

# Transpose
print("A transposed:\n", A.T)

Matrix A:
 [[1 2]
 [3 4]]
A + B:
 [[ 6  8]
 [10 12]]
A * B (element-wise):
 [[ 5 12]
 [21 32]]
A dot B:
 [[19 22]
 [43 50]]
A transposed:
 [[1 3]
 [2 4]]


### Using SymPy for Symbolic Matrices

In [2]:
import sympy as sp

# Define symbolic variables
a, b, c, d = sp.symbols('a b c d')
M = sp.Matrix([[a, b], [c, d]])
print("Symbolic Matrix M:\n", M)

# Determinant
print("Determinant of M:", M.det())

# Inverse
if M.det() != 0:
    print("Inverse of M:\n", M.inv())

Symbolic Matrix M:
 Matrix([[a, b], [c, d]])
Determinant of M: a*d - b*c
Inverse of M:
 Matrix([[d/(a*d - b*c), -b/(a*d - b*c)], [-c/(a*d - b*c), a/(a*d - b*c)]])


## 2. Applications: Linear Transformations

A matrix can represent a linear transformation in space.

### Example: 2D Rotation Transformation

In [3]:
import numpy as np

theta = np.pi / 4  # 45 degrees
rotation_matrix = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]
])
vector = np.array([1, 0])

# Apply rotation
rotated_vector = rotation_matrix @ vector
print("Rotated vector:", rotated_vector)

Rotated vector: [0.70710678 0.70710678]


## 3. Solving Systems of Linear Equations

Suppose you have the system:
$
\begin{cases}
2x + 3y = 8 \\
x - 4y = -2
\end{cases}
$

### Using NumPy

In [4]:
import numpy as np

A = np.array([[2, 3], [1, -4]])
b = np.array([8, -2])

# Solve for [x, y]
solution = np.linalg.solve(A, b)
print("Solution [x, y]:", solution)

Solution [x, y]: [2.36363636 1.09090909]


### Using SymPy (Symbolic Solution)

In [5]:
import sympy as sp

x, y = sp.symbols('x y')
eq1 = sp.Eq(2*x + 3*y, 8)
eq2 = sp.Eq(x - 4*y, -2)
solution = sp.solve((eq1, eq2), (x, y))
print("Symbolic solution:", solution)

Symbolic solution: {x: 26/11, y: 12/11}


## 4. Matrix Inverse and Determinant

- The **determinant** indicates if a matrix is invertible (non-zero determinant means invertible).
- The **inverse** is used to "undo" the linear transformation or solve equations $Ax = b$ via $x = A^{-1}b$.

In [6]:
import numpy as np

A = np.array([[2, 3], [1, -4]])
det = np.linalg.det(A)
print("Determinant:", det)

if det != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)

Determinant: -11.000000000000002
Inverse of A:
 [[ 0.36363636  0.27272727]
 [ 0.09090909 -0.18181818]]


## 5. Eigenvalues and Eigenvectors

These are fundamental in understanding linear transformations, especially for diagonalization and applications in physics and machine learning.

In [7]:
import numpy as np

A = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


---

## 6. Practice: Try Your Own

Change the matrices and systems above to practice different operations, or create higher-dimensional matrices.

---

## 7. Further Reading

- [NumPy Linear Algebra](https://numpy.org/doc/stable/reference/routines.linalg.html)
- [SymPy Matrices](https://docs.sympy.org/latest/modules/matrices/matrices.html)
- [Matrix (mathematics) - Wikipedia](https://en.wikipedia.org/wiki/Matrix_%28mathematics%29)
- [Linear Algebra - Khan Academy](https://www.khanacademy.org/math/linear-algebra)

# [College Algebra Context](./README.md)